### ISSUE TITLE
Correction sur le regex avec choix multiples

### ISSUE THREAD

**Issue by raphodn** [datagistips/memos#1]
Salut ! super initiative :)

1) Sur le regex `Valeurs séparées par un | (Public cible)` l'exemple est erroné, cela devrait être `Tout public,Allocataires,Demandeurs d'emploi`.
    - testable ici : https://regexr.com/5t28l
    - pour contexte, je suis le dev qui l'a "créé" sur [le schéma des lieux d'inclusion numérique](https://schema.data.gouv.fr/etalab/schema-inclusion-numerique/latest/documentation.html)
    - et c'est du WIP, on se pose plein de questions pour l'améliorer... https://github.com/frictionlessdata/specs/issues/736

2) A l'image du regex ci-dessus, peut-être proposer parfois plusieurs exemples ? Comme `Tout public` & `Tout public,Allocataires`

3) Et pendant que j'y suis dans les idées qui me viennent, peut-être une colonne additionnelle avec un lien vers un schéma qui utilise le regex en question ?

Voilà hope it helps

**Comment by datagistips** [comment]
Bonjour,

Merci beaucoup
Je viens de créer une colonne schéma et ai mis le lien vers le champ dans le schéma des lieux d'inclusion numérique, et mis le multi-exemple.
